apiVersion: v1
data:
  enable-vpc-nat-gw: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"enable-vpc-nat-gw":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"ovn-vpc-nat-gw-config","namespace":"kube-system"}}
  creationTimestamp: "2025-11-07T17:51:35Z"
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
  resourceVersion: "3926040"
  uid: 2ce03b0d-f711-43fb-9aea-953e34229ab3
