apiVersion: v1
data:
  image: docker.io/kubeovn/vpc-nat-gateway:v1.15.0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"image":"docker.io/kubeovn/vpc-nat-gateway:v1.15.0"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"ovn-vpc-nat-config","namespace":"kube-system"}}
  creationTimestamp: "2025-11-07T17:51:35Z"
  name: ovn-vpc-nat-config
  namespace: kube-system
  resourceVersion: "3926039"
  uid: faf6fc27-7cf5-4782-b939-0e78c76cf281

